version: "3.9"
services:

    
    
    chat-ui:
        build: ./chatui
        ports:
            - "80:80"
        volumes:
            - '.:/app'
            - '/app/node_modules'
        environment:
            - CHOKIDAR_USEPOLLING=true

    image_classification_api:
        build: ./API/Image_Classification_API
        ports:
            - "5001:5001"
        volumes:
            - '.:/image_classification_api'

    symptoms_classification_api:
        build: ./API/Symptoms_Classification_API
        ports:
            - "5002:5002"
        volumes:
            - '.:/symptoms_classification_api'


    treatment_recommender_api:
        build: ./API/Treatment_Recommender_API
        ports:
            - "5003:5003"
        volumes:
            - '.:/treatment_recommender_api'
