# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FCx8JyeJIh7hSy1TFuBjal6pLRihItS2
"""

# !pip install flask-restful
# !pip install flask_cors
# !pip install -U flask-cors
from flask_cors import CORS
import flask


import sqlite3


app = flask.Flask(__name__)
CORS(app)




@app.route("/predict", methods=["POST"])
def predict():
  response={"treatment":"Invalid Disease"}

  if flask.request.method=='POST': 

    disease=flask.request.form["disease"]
    print(disease)

    connection = sqlite3.connect(":memory:")
    cursor = connection.cursor()
    sql_file = open("treatments.sql")
    sql_as_string = sql_file.read()
    cursor.executescript(sql_as_string)
    
    
    cursor.execute("select treatment from treatments where disease_name='{}'".format(disease))

    treatment_data=""
    for treatment in cursor:
      treatment_data=treatment[0]
    response["treatment"]=treatment_data

  return flask.jsonify(response)

if __name__=="__main__":  
  app.run(host='0.0.0.0',port=5003,debug=False)

