# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FCx8JyeJIh7hSy1TFuBjal6pLRihItS2
"""

!pip install flask-restful
!pip install flask_cors
!pip install -U flask-cors
from flask_cors import CORS
import flask
from flask import Flask,jsonify
import pandas as pd
import ast
from flask import request


app = flask.Flask(__name__)
CORS(app)
@app.route("/predict", methods=["POST"])
def predict():
   text=flask.request.form["text"]
   df=pd.read_csv('2.csv')
   for i in range(len(df)):
     if df.iloc[i,0]==text:
       return df.iloc[i,1]

app.run(host='0.0.0.0',port=5002)
